### ISSUE TITLE
Storage patching fails for fields on proxy models

### ISSUE THREAD

**Issue by melinath** [danifus/django_override_storage#4]
It turns out that proxy models re-use field instances, which means that during the first call to `setup_storage` the wrapping gets messed up.

Suppose you have a field `image` that appears on a model that has a proxy of it. During setup_storage, the following might happen:

1. The field on the proxy model gets overridden. Default storage is stored in `previous_storages` for the field, and then LocMemStorage is set as the field's storage.
2. The field on the main model gets overridden. It's the same instance. LocMemStorage is stored in `previous_storages` for the field, and then LocMemStorage is set as the field's storage.

I think the solution here might be to ignore proxy models when overriding file fields, though it might also work to make filefields a set rather than a list.

**Comment by melinath** [comment]
(Sorry I didn't see this before - it was drowned out by the previous error. I promise this is the only issue I'm seeing now, though!)

**Comment by danifus** [comment]
No worries - send all the bugs you find through anytime you find them!

This should be fixed by 8f21cc37c72a591fa376c85c56a13e8ca15b4cc5. Let me know if it is still an issue for you. The new version is up on PyPI too.

Thanks again!

**Comment by melinath** [comment]
Yep, that works now! Thanks!
