### ISSUE TITLE
Class decorator doesn't work for models created in setUpTestData

### ISSUE THREAD

**Issue by MrkGrgsn** [danifus/django_override_storage#5]
Thanks for a very useful library, it fits what I need perfectly. I'm trying to run some tests on a model instance that is created and has a file added in `setUpTestData()`. The whole test class is decorated with `@override_settings()`.  If I drop into PDB during one of the test methods, the `FieldFile` object has the original `name` and it's storage attribute is a `LocMemStorage` object but the storage doesn't contain the file, ie, `my_file.storage.exists(my_file.name)` returns `False`. 

If I shift all the file saving from `setUpTestData()` to the test method then it works as I expect: the storage contains the file.

Is this a supported pattern for building test data?

**Comment by danifus** [comment]
I've never tried to create any files in the `setUpTestData()` method but there are probably two problems I can see. The first is the underlying machinery. `override_storage` uses django's `TestContextDecorator` (https://github.com/django/django/blob/master/django/test/utils.py#L323) to get similar behaviour to `override_settings`. Unfortunately, `TestContextDecorator` wraps `setUp()` which is called after `setUpTestData()`.

The second is test case isolation. In `LocMemStorage` and `StorageTestMixin` there is no notion of a 'snapshot' of what files were around before the test or the ability to roll back to that state at the end of the test. You can create storages which persist files across all tests so you may be able to combine a modified `LocMemStorage` and `StorageTestMixin` to make something that is created before `setUpTestData()` and gives you snapshot behaviour in setUp and tearDown.

**Comment by MrkGrgsn** [comment]
Thanks for speedy response. I think I will just accept that's the way it works and use `setUp()` as necessary.
